web:
  build: images/nginx
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - mysql:mysql
    - memcached:memcached
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/sites-enabled

mysql:
  image: dgraziotin/mysql
  ports:
    - "3306:3306"
# Uncomment to persist database to /mysql directory    
#  volumes:
#    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ADMIN_PASS: password

memcached:
  build: images/memcached
  ports:
    - "11211:11211"

redis:
  image: tutum/redis
  ports:
    - "6379:6379"
  environment:
    REDIS_PASS: password
