version: "3"
services:
  webserver:
    build: images/nginx
    ports:
      - "80:80"
      - "9099:22"
    volumes:
      - ./www:/var/www:delegated
      - ./sites:/etc/nginx/sites-enabled:delegated
      - ./php:/etc/php/7.2/fpm:delegated
    networks:
      default:
        aliases:
          - webspark.d

  selenium_server:
    image: selenium/standalone-chrome-debug:2.53.1
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 2G
    environment:
      HUB_ENV_no_proxy:
    networks:
      default:
        aliases:
          - selenium_server

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
    networks:
      default:
        aliases:
          - mariadb

  memcached:
    build: images/memcached
    ports:
      - "11211:11211"
    networks:
      default:
        aliases:
          - memcached

  redis:
    image: tutum/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASS: password
    networks:
      default:
        aliases:
          - redis

  # Uncomment to run Node container
  #node:
  #  image: "node:latest"
  #  user: "node"
  #  working_dir: /home/node/app
  #  environment:
  #    - NODE_ENV=development
  #  volumes:
  #    - ./node:/home/node/app:delegated
  #  ports:
  #    - "8081:8081"
  #    - "3000:3000"
  #    - "5000:5000"
  #  command: ['npm', 'start:dev']
  #  networks:
  #    default:
  #      aliases:
  #        - node