version: "3"
services:
  webserver:
    build: images/nginx
    ports:
      - "80:80"
      - "9099:22"
    links:
      - mariadb:mariadb
      - memcached:memcached
      - redis:redis
      - node:node
      - selenium_server:selenium_server
    volumes:
      - ./www:/var/www:delegated
      - ./sites:/etc/nginx/sites-enabled:delegated
      - ./php:/etc/php/7.2/fpm:delegated

  selenium_server:
    image: selenium/standalone-chrome-debug:2.53.1
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      HUB_ENV_no_proxy:
  # Uncomment lines to run selenium_server
  # If trouble starting up, see issue:  https://github.com/SeleniumHQ/docker-selenium/issues/91

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    #volumes:
    #  - ./mysql/mysql:/var/lib/mysql
    #  - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin

  memcached:
    build: images/memcached
    ports:
      - "11211:11211"

  redis:
    image: tutum/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASS: password

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./node/unity:/home/node/app:delegated
    ports:
      - "8081:8081"
      - "3000:3000"
      - "5000:5000"
    command: ['npm', 'start:dev']